<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/21 14:31:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jeanallouchbibliotheque',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
